<a href="https://colab.research.google.com/github/Anitayea/Linear_and_Nonlinear_Optimization/blob/main/HW3draft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider a zero-sum game with payoff matrix $\prod_{ij}$ where I =
J = {1,...,n}. Assume $\prod_{ij}$ is antisymmetric: $\prod_{ij} = - \prod_{ji}$ 

(i) Show that if the game has an equilbrium in pure strategy, then the value of the game for both players is zero.

If the game has equilibrium in pure strategy,

$j^* = J(i^*), i^* = I(j^*)$, and 

$ \prod _{i*j*} = min_j \prod_{i*j} = max_i \prod_{ij*} $

$\because min_j \prod_{i*j} = min_j max_i \prod_{ij}$

$max_i \prod_{ij*} = max_i min_j \prod_{ij}$

$\therefore min_j max_i \prod_{ij} = max_i min_j \prod_{ij}$


since it is a zero sum game, player 1's payoff is $\prod_{ij}$ and player 2's payoff is $-\prod_{ij}$

since the matrix is antisymmetric,

$\prod_{ij} = - \prod_{ji}$

$\because I=J$

$\therefore m=n,$ full rank

$\because$ equilibrium

$\therefore \prod _{i*j*} = min_j \prod_{i*j} = max_j \prod_{ij*} $

$\therefore min_j \prod_{i*j} = - min_j \prod_{ij*} $

$\because \prod_{ij} = - \prod_{ji}$

$\therefore  \prod_{ij} = - \prod_{ij} $

Therefore, payoffs of 1 and 2 are the same and =0


$\therefore -\prod_{ji} = -\prod_{ij} = 0$



\\

From the question:

$\because \prod_{ij} = - \prod_{ji}$

$ min \prod_{ij} = -min\prod_{ji} = max \prod_{ji}$

To satisfy both the antisymmetric and the equilibrium,

$\therefore i^* = j^* = 0$



#---

$\because I=J$

$\therefore$ matrix is full rank with $m=n$

$\because \prod_{ij} = - \prod_{ji}$

$\therefore \prod _{i*j*} = - \prod_{j*i*}$

$ min_j \prod_{i*j} = max_j \prod_{ij*}$






\begin{align}
  min \quad 2x_1 + 3x_2 &-x_3\\
  s.t. \quad x_1+x_2 &\leq 1\\
  x_3 &\leq 2\\
\end{align}


(ii) Show that the game has an equilibrium in pure strategy if and only if there is a $i^*$ such that $\prod_{i^*j} \geq 0 \quad \forall j$

(iii) Show that the value to player 1 of the game in a mixed strategy is zero

(iv) Use gurobi if needed, compute an equilibrium in mixed *strategy*

In [1]:
!pip install gurobipy

     |████████████████████████████████| 11.5 MB 6.8 MB/s 


In [2]:
import numpy as np
import gurobipy as grb
import scipy.sparse as spr
import pandas as pd

In [5]:
Pi_i_j = np.array([[0, -3, -1, 2], 
                    [3, 0, 2, 5], 
                    [1, -2, 0, -1],
                   [-2, -5, 1, 0]])
Pi_i_j

array([[ 0, -3, -1,  2],
       [ 3,  0,  2,  5],
       [ 1, -2,  0, -1],
       [-2, -5,  1,  0]])

In [6]:
matrixgame_model = grb.Model()
nbi,nbj = Pi_i_j.shape
p_iv = matrixgame_model.addMVar(shape = nbi)
sv = matrixgame_model.addMVar(1, lb = - grb.GRB.INFINITY )
matrixgame_model.setObjective(sv, grb.GRB.MAXIMIZE)
matrixgame_model.addConstr( np.ones( (nbj,1) ) @ sv - Pi_i_j.T @ p_iv   <=0  )
matrixgame_model.addConstr( p_iv.sum()==1 )
matrixgame_model.optimize() 


Restricted license - for non-production use only - expires 2023-10-25
Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (linux64)
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads
Optimize a model with 5 rows, 5 columns and 20 nonzeros
Model fingerprint: 0x48b8a347
Coefficient statistics:
  Matrix range     [1e+00, 5e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 1 rows and 1 columns
Presolve time: 0.01s
Presolved: 4 rows, 4 columns, 15 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    3.0000000e+00   1.000000e+00   0.000000e+00      0s
       1   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 1 iterations and 0.02 seconds (0.00 work units)
Optimal objective -0.000000000e+00


In [7]:
p_i = np.array(matrixgame_model.getAttr('x'))[:-1]
p_i

array([0., 1., 0., 0.])

In [8]:
q_j = np.array(matrixgame_model.getAttr('pi'))[:-1]
q_j

array([0., 1., 0., 0.])

In [9]:
np.array(matrixgame_model.getAttr('x'))[-1]

0.0

In [10]:
np.array(matrixgame_model.getAttr('pi'))[-1]

-0.0

(v) Equilibrium in pure strategy?


2.

\begin{align}
  V_{12} = max_{p_i \geq 0} \quad &s\\
  s.t. \quad &s \leq ∑_i pi\prod_{ij} \quad \forall j \in J\\
  &∑_{i\in I} p_i = 1 [t]\\
\end{align}

(a) let $x_i - p_i/s$

\begin{align}
  V_{12} = \quad &max_{x_i \geq 0} \quad s\\
  s.t. \quad &∑_{i \in I} x_i\prod_{ij} \geq 1\\
  &∑_{i\in I} x_i = 1/s\\
\end{align}

therefore:

\begin{align}
  V_{12} = \quad &max_{x_i \geq 0} \quad 1 / ∑_{i \in I} x_i\\
  s.t. \quad &∑_{i \in I} x_i\prod_{ij} \geq 1\\
\end{align}

hence:

\begin{align}
  1/V_{12} = \quad &min_{x_i \geq 0} \quad ∑_{i \in I} x_i\\
  s.t. \quad &∑_{i \in I} x_i\prod_{ij} \geq 1\\
\end{align}


b) compute the dual to(1) and show that it coincides with $min_{q\in \vartriangle_J} max_{q\in \vartriangle_I} p^T \prod q$ 

The dual problem for $V_{12} = V_{21}:$

\begin{align}
  1/V_{21} = \quad &max_{y_j \geq 0} \quad ∑_{j \in J} y_i\\
  s.t. \quad &∑_{j \in J} y_i\prod_{ij} \leq 1\\
\end{align}

since both LPs are feasible, by strong duality, they coincide, which means that $V_{21} = V_{12}$

Denote $x^*$ to be the optimal solution to $V_{12}$ and $y^*$ to $V_{21}$, we have:

$p_i^* = x_i^*/ ∑_{i \in I}x_i^*, q_j^* = y_j^*/ ∑_{j \in J}y_j^*$

which gives us

$(p^*)^T \prod q^* = min_{q \in \vartriangle_J} (p^*)^T \prod q = max_{p \in \vartriangle_I} p^T \prod q^*$

which means that there exist a optimal solution $(p^*, q^*) that is the equilibrium in mixed strategy.

(c) Deduce value of the game, and eq strategies

min-cost flow 

primal:

\begin{align}
  min_{\mu \geq 0} \quad &\mu^T c\\
  s.t. \quad &M \mu = q\\
\end{align}

dual:

\begin{align}
  max_p \quad &∑_{z\in Z} q_z p_z\\
  s.t. \quad &M^Tp \leq c\\
\end{align}

3. There is a feasible sol for primal iff $∑_z q_z = 0$ and for every subset $B \subseteq Z$ such that there is no $xy \in A$ with $ x\in B, y \notin B$, we have $∑_{z\in B} q_z \geq 0$
for a and b assume feasible sol for primal sol $\mu$, $\mu \geq 0, M\mu = q$


see p 116 but I still dont understand

a) Show that $∑_{z\in Z} q_z = 0$