<a href="https://colab.research.google.com/github/Anitayea/Linear_and_Nonlinear_Optimization/blob/main/Lomid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gurobipy
import numpy as np
import gurobipy as grb
import scipy.sparse as spr
import pandas as pd


     |████████████████████████████████| 11.5 MB 3.5 MB/s 


In [ ]:
#5
Pi_i_j = np.array([[2,1,0,0], 
                    [0,0,3,4],
                   [2,0,3,0],
                   [0,1,0,4]])
Pi_i_j



array([[2, 1, 0, 0],
       [0, 0, 3, 4],
       [2, 0, 3, 0],
       [0, 1, 0, 4]])

In [ ]:
matrixgame_model = grb.Model()
nbi,nbj = Pi_i_j.shape
p_iv = matrixgame_model.addMVar(shape = nbi)
sv = matrixgame_model.addMVar(1, lb = - grb.GRB.INFINITY )
matrixgame_model.setObjective(sv, grb.GRB.MAXIMIZE)
matrixgame_model.addConstr( np.ones( (nbj,1) ) @ sv - Pi_i_j.T @ p_iv   <=0  )
matrixgame_model.addConstr( p_iv.sum()==1 )
matrixgame_model.optimize() 

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (linux64)
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads
Optimize a model with 5 rows, 5 columns and 16 nonzeros
Model fingerprint: 0x7adc27df
Coefficient statistics:
  Matrix range     [1e+00, 4e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 1 rows and 0 columns
Presolve time: 0.01s
Presolved: 4 rows, 5 columns, 17 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    2.0000000e+00   1.503000e+00   0.000000e+00      0s
       2    7.5000000e-01   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.02 seconds (0.00 work units)
Optimal objective  7.500000000e-01


In [ ]:
p_i = np.array(matrixgame_model.getAttr('x'))[:-1]
p_i

array([0.375, 0.25 , 0.   , 0.375])

In [ ]:
q_j = np.array(matrixgame_model.getAttr('pi'))[:-1]
q_j

array([-0.  ,  0.75,  0.25,  0.  ])

In [ ]:
np.array(matrixgame_model.getAttr('x'))[-1]

0.75

In [ ]:
np.array(matrixgame_model.getAttr('pi'))[-1]

0.75

In [ ]:
#6
M_z_a = np.array(
    [[-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,0,0,0,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,0,0,0,0,0,0,0,-1,-1,-1,-1,0,0,0,0,0,0,0,0],
     [0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,0,0,0,0],
     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1],
     [1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],
     [0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0],
     [0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0],
     [0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1]])

q_z = np.array([-3,-4,-6,-2,-5,3,7,6,4])

c_a = np.array([10,45,15,10,5,25,30,25,35,15,20,15,75,40,35,30,20,60,5,65])

In [ ]:
mincostflow =grb.Model()
nbz,nba = M_z_a.shape
mu_a = mincostflow.addMVar(shape=nba)
mincostflow.setObjective( mu_a @ c_a, grb.GRB.MINIMIZE)
mincostflow.addConstr(M_z_a @ mu_a == q_z)
mincostflow.optimize()

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (linux64)
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads
Optimize a model with 9 rows, 20 columns and 40 nonzeros
Model fingerprint: 0xfcaa41d6
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [5e+00, 8e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+00, 7e+00]
Presolve time: 0.03s
Presolved: 9 rows, 20 columns, 40 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.9000000e+02   6.000000e+00   0.000000e+00      0s
       4    2.5000000e+02   0.000000e+00   0.000000e+00      0s

Solved in 4 iterations and 0.06 seconds (0.00 work units)
Optimal objective  2.500000000e+02


In [ ]:
M_z_a = np.array(
    [[-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,0,0,0,0,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0],
     [0,0,0,0,0,0,0,0,-1,-1,-1,-1,0,0,0,0,0,0,0,0],
     [0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,0,0,0,0],
     [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1],
     [1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],
     [0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0],
     [0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0],
     [0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1]])

q_z = np.array([-3,-4,-6,-2,-5,3,7,6,4])

c_a = np.array([10,45,15,10,5,25,30,25,35,15,20,15,75,40,35,30,20,60,5,65])

In [ ]:
mincostflow =grb.Model()
nbz,nba = M_z_a.shape
mu_a = mincostflow.addMVar(shape=nba)
mincostflow.setObjective( mu_a @ c_a, grb.GRB.MINIMIZE)
mincostflow.addConstr(M_z_a @ mu_a == q_z)
mincostflow.optimize()

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (linux64)
Thread count: 1 physical cores, 2 logical processors, using up to 2 threads
Optimize a model with 9 rows, 20 columns and 38 nonzeros
Model fingerprint: 0xb152894a
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [5e+00, 8e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+00, 7e+00]
Presolve removed 0 rows and 1 columns
Presolve time: 0.02s
Presolved: 9 rows, 19 columns, 38 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    2.0500000e+02   1.498300e+01   0.000000e+00      0s
       6    3.1000000e+02   0.000000e+00   0.000000e+00      0s

Solved in 6 iterations and 0.03 seconds (0.00 work units)
Optimal objective  3.100000000e+02
